setting up Miniconda...
activating virtual env...
current conda environment: basic310
activating ssh connection...
Agent pid 2565485
Identity added: /home/11864265/.ssh/id_ed25519 (11864265@fnwi-h0.science.uva.nl)
parsing input arguments...
Branch: feature/retrain
fetching and pulling latest changes from remote dir...
Already up to date.
retraining the models...
Creating output dir
Running script for version 
Traceback (most recent call last):
  File "/home/11864265/Documents/thesis_code/retrain/eval.py", line 49, in <module>
    args = set_experiment_config(args)
  File "/home/11864265/Documents/thesis_code/retrain/utils.py", line 27, in set_experiment_config
    raise ValueError(f'Data directory {args.data_dir} does not exist.')
ValueError: Data directory /scratch/11864265/results does not exist.
srun: error: fnwi-cn005: task 0: Exited with exit code 1
Creating output dir
Running script for version 
Traceback (most recent call last):
  File "/home/11864265/Documents/thesis_code/retrain/eval.py", line 49, in <module>
    args = set_experiment_config(args)
  File "/home/11864265/Documents/thesis_code/retrain/utils.py", line 27, in set_experiment_config
    raise ValueError(f'Data directory {args.data_dir} does not exist.')
ValueError: Data directory /scratch/11864265/results does not exist.
srun: error: fnwi-cn005: task 0: Exited with exit code 1
adding, committing, and pushing results to remote dir...
